{% set version = "6.0.0" %}

package:
  name: wasmer
  version: {{ version }}

source:
  url: https://github.com/wasmerio/wasmer/archive/v{{ version }}.tar.gz
  sha256: 07ab0bfc73f0add8617de74c363f558686e9598ba194c7c8804e7cea9996397e

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - pkg-config    # [linux]
  host:
    - libffi
    - openssl
    - zlib
    - libxkbcommon  # [linux]
    - llvm-tools    # [linux]
    - llvmdev       # [linux]
    - zstd          # [linux]
  run:
    - zstd          # [linux]

test:
  source_files:
    - tests/wasi-wast/wasi/snapshot1/hello.wasm
  requires:
    - pytest
    - m2-grep  # [win]
  commands:
    - wasmer --version
    - wasmer --version | grep -ie {{ version.replace(".", "\\.") }}
    - wasmer --help

about:
  home: https://wasmer.io
  license: MIT
  license_family: MIT
  summary: Universal WebAssembly runtime
  description: |
    Wasmer is a standalone JIT WebAssembly runtime, aiming to be fully
    compatible with WASI and Emscripten.
  dev_url: https://github.com/wasmerio/wasmer
  doc_url: https://docs.wasmer.io
  doc_source_url: https://github.com/wasmerio/docs.wasmer.io
  license_file:
    - LICENSE
    - docs/ATTRIBUTIONS.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
    - wolfv
