{% set version = "4.3.4" %}

package:
  name: wasmer
  version: {{ version }}

source:
  url: https://github.com/wasmerio/wasmer/archive/v{{ version }}.tar.gz
  sha256: 0e18c0aedec7f62d1397091501332af1e0b164c75f25a44743db96a52c5ee688

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - rust ==1.74.*  # [linux]
    - cargo-bundle-licenses
    # TODO: investigate for osx?
    - llvmdev >=15,<16  # [linux]
    - llvm-tools  # [linux]
    - pkg-config  # [linux]
  host:
    - libffi
    - libxkbcommon  # [linux]
    - openssl
    - zlib
    - zstd  # [linux]
  run:
    - zstd  # [linux]

{% set test_wasm = "tests/wasi-wast/wasi/snapshot1/hello.wasm" %}
{% set test_text = "Hello, world!" %}
{% set backends = ["singlepass", "cranelift"] %}
{% set backends = backends + ["llvm"] %}  # [linux]

test:
  source_files:
    - {{ test_wasm }}
  requires:
    - m2-grep  # [win]
  commands:
    - wasmer --version
    - wasmer --version | grep -ie '{{ version.replace(".", "\\.") }}'
    - wasmer --help
    {% for backend in backends %}
    - wasmer run --{{ backend }} {{ test_wasm }}
    - wasmer run --{{ backend }} {{ test_wasm }} | grep '{{ test_text }}'
    - wasmer validate --{{ backend }} {{ test_wasm }}
    # TODO: test engines?
    # TODO: test compile?
    # TODO: test exe?
    # - WASMER_DIR=$PREFIX wasmer create-exe --{{ backend }} {{ test_wasm }} -o ./hello-{{ backend }}
    # - ./hello-{{ backend }}
    # - ./hello-{{ backend }} | grep '{{ test_text }}'
    {% endfor %}

about:
  home: https://wasmer.io
  license: MIT
  license_family: MIT
  summary: Universal WebAssembly runtime
  description: |
    Wasmer is a standalone JIT WebAssembly runtime, aiming to be fully
    compatible with WASI and Emscripten.
  dev_url: https://github.com/wasmerio/wasmer
  doc_url: https://docs.wasmer.io
  doc_source_url: https://github.com/wasmerio/docs.wasmer.io
  license_file:
    - LICENSE
    - docs/ATTRIBUTIONS.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
    - wolfv
