# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "7.1.0"

package:
  name: wasmer
  version: ${{ version }}

source:
  url: https://github.com/wasmerio/wasmer/releases/download/v${{ version }}/wasmer-full-source.tar.xz
  sha256: 4a4374e84f55758de2f8b57b3f5a88015d5f9341b6417601c372138ab90f9fa4

build:
  number: 0
  script:
    file: build-wasmer

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: linux
      then:
        - pkg-config
  host:
    - libffi
    - openssl
    - zlib
    - if: linux
      then:
        - libxkbcommon
        - libxml2-devel
        - llvm-tools
        - llvmdev
        - zstd
  run:
    - if: linux
      then:
        - zstd

tests:
  - files:
      recipe:
        - run_test.py
      source:
        - tests/wasi-wast/wasi/snapshot1/hello.wasm
    requirements:
      run:
        - pytest
        - if: win
          then:
            - m2-grep
    script:
      - wasmer --version
      - wasmer --version | grep -ie "${{ version | replace(".", "\\.") }}"
      - wasmer --help
      - python run_test.py

about:
  license: MIT
  summary: Universal WebAssembly runtime
  description: |
    Wasmer is a standalone JIT WebAssembly runtime, aiming to be fully
    compatible with WASI and Emscripten.
  license_file:
    - LICENSE
    - lib/c-api/tests/wasm-c-api/LICENSE
    - lib/compiler-llvm/LICENSE
    - lib/compiler-singlepass/LICENSE
    - lib/config/LICENSE
    - tests/wasi-fyi/LICENSE
    - tests/wast/spec/LICENSE
  homepage: https://wasmer.io
  repository: https://github.com/wasmerio/wasmer
  documentation: https://docs.wasmer.io

extra:
  recipe-maintainers:
    - bollwyvl
    - wolfv
