# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "7.1.0"

package:
  name: wasmer
  version: ${{ version }}

source:
  - url: https://github.com/wasmerio/wasmer/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 8c7c383db5141745ba4af85d718224f8c6c7551531567cc657cb516a2a62c734
  - target_directory: lib/napi  # (heads/main)
    url: https://github.com/wasmerio/napi/archive/9d2dae0ea425788dfa7c5a31d184686d616235bb.tar.gz
    sha256: 3901b54b5a7901bae20ed121a0224618d40c1b47d79580a2b5620997c20159b4
  - target_directory: tests/wast/spec  # (7e0b83a)
    url: https://github.com/WebAssembly/testsuite/archive/7e0b83aba9dbbb6e0623c9334b0f73b3bb584b90.tar.gz
    sha256: 24b42135bf95cc1c2f4afd30b6f3f718116b921e4a0f4c76ace605e3883c134d
build:
  number: 0
  script:
    file: build-wasmer

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: linux
      then:
        - pkg-config
  host:
    - libffi
    - openssl
    - zlib
    - if: linux
      then:
        - libxkbcommon
        - libxml2-devel
        - llvm-tools
        - llvmdev
        - zstd
  run:
    - if: linux
      then:
        - zstd

tests:
  - files:
      recipe:
        - run_test.py
      source:
        - tests/wasi-wast/wasi/snapshot1/hello.wasm
    requirements:
      run:
        - pytest
        - if: win
          then:
            - m2-grep
    script:
      - wasmer --version
      - wasmer --version | grep -ie "${{ version | replace(".", "\\.") }}"
      - wasmer --help
      - python run_test.py

about:
  license: MIT
  summary: Universal WebAssembly runtime
  description: |
    Wasmer is a standalone JIT WebAssembly runtime, aiming to be fully
    compatible with WASI and Emscripten.
  license_file:
    - LICENSE
    - lib/c-api/tests/wasm-c-api/LICENSE
    - lib/compiler-llvm/LICENSE
    - lib/compiler-singlepass/LICENSE
    - lib/config/LICENSE
    - tests/wasi-fyi/LICENSE
    - tests/wast/spec/LICENSE
  homepage: https://wasmer.io
  repository: https://github.com/wasmerio/wasmer
  documentation: https://docs.wasmer.io

extra:
  recipe-maintainers:
    - bollwyvl
    - wolfv
