# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "7.4.1"
  cowsay_wasm: wasmer-test-files/integration/wasm/cowsay.wasm
  # features neded for basic wasmer-cli functionality
  ft_default: wasm-c-api wasmer-artifact-create static-artifact-create wasmer-artifact-load static-artifact-load
  # other features not available on all platforms
  ft_v8: ${{ "" if target_platform in ["linux-aarch64", "osx-64"] else "v8" }}
  ft_linux: ${{ "" if not linux else "llvm" }}
  ft_unix: ${{ "" if not unix else "cranelift singlepass" }}
  ft_backends: ${{ [ft_v8, ft_linux, ft_unix] | join(" ") }}
  features: ${{ [ft_default, ft_backends] | join(" ") | split | sort | join(",") }}

package:
  name: wasmer
  version: ${{ version }}

source:
  url: https://github.com/wasmerio/wasmer/releases/download/v${{ version }}/wasmer-full-source.tar.gz
  sha256: 038fc2a5caf10419f09f489d35fd962408b43ddc6cbb0214062343b7f45e5ea6

build:
  number: 0
  script:
    env:
      FEATURES: ${{ features }}
    file: build-wasmer

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    # see: https://github.com/wasmerio/wasmer/issues/6606
    # - cargo-auditable
    - cargo-bundle-licenses
    - pkg-config
  host:
    - libffi
    - openssl
    - zlib
    - if: linux
      then:
        - clangdev
        - libxkbcommon
        - libxml2-devel
        - llvm-tools
        - llvmdev
        - zstd
  run:
    - if: linux
      then:
        - zstd

tests:
  - files:
      recipe:
        - run_test.py
      source:
        - ${{ cowsay_wasm }}
    requirements:
      run:
        - pytest
    script:
      env:
        COWSAY_WASM: ${{ cowsay_wasm }}
        BACKENDS: ${{ ft_backends }}
      content:
        - wasmer --version
        - wasmer --help
        - wasmer run --help
        - python run_test.py

about:
  license: MIT
  summary: Universal WebAssembly runtime
  description: |
    Wasmer is a standalone JIT WebAssembly runtime, aiming to be fully
    compatible with WASI and Emscripten.
  license_file:
    - LICENSE
    - THIRDPARTY.yml
    - docs/ATTRIBUTIONS.md
  homepage: https://wasmer.io
  repository: https://github.com/wasmerio/wasmer
  documentation: https://docs.wasmer.io

extra:
  recipe-maintainers:
    - bollwyvl
    - wolfv
